export const CLIENT_SENDS_ENCRYPTION_SIGNAL = "CLIENT_SENDS_ENCRYPTION_SIGNAL";
export const SERVER_RECEIVES_ENCRYPTION_SIGNAL = "SERVER_RECEIVES_ENCRYPTION_SIGNAL";
export const CLIENT_SENDS_DECRYPTION_SIGNAL = "CLIENT_SENDS_DECRYPTION_SIGNAL";

export const SERVER_SENDS_PROCESSING_PROGRESS = "SERVER_SENDS_PROCESSING_PROGRESS";
export const SERVER_FINISHES_ENCRYPTION = "SERVER_FINISHES_ENCRYPTION";
export const SERVER_FINISHES_COMPRESSION = "SERVER_FINISHES_COMPRESSION";

export const CLIENT_SENDS_FOLDER_ENCRYPTION_SIGNAL = "CLIENT_SENDS_FOLDER_ENCRYPTION_SIGNAL";
export const CLIENT_SENDS_FOLDER_DECRYPTION_SIGNAL = "CLIENT_SENDS_FOLDER_DECRYPTION_SIGNAL";

export const SERVER_SENDS_ERROR_MESSAGE = "SERVER_SENDS_ERROR_MESSAGE";